### ISSUE TITLE
Install script error : fe_sendauth: no password supplied

### ISSUE THREAD

**Issue by sbnsec** [Patrowl/PatrowlManager#247]
Hello,

I'm trying to install PatrowlManager for the first time to try it :)

During the install process I got a lot of theses errors : 

```
+ echo '[+] Make database migrations'
[+] Make database migrations
+ python manage.py makemigrations
Traceback (most recent call last):
  File "/home/debian/PatrowlHears-master/backend_app/env/lib/python3.9/site-packages/django/db/backends/base/base.py", line 219, in ensure_connection
    self.connect()
  File "/home/debian/PatrowlHears-master/backend_app/env/lib/python3.9/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "/home/debian/PatrowlHears-master/backend_app/env/lib/python3.9/site-packages/django/db/backends/base/base.py", line 200, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/home/debian/PatrowlHears-master/backend_app/env/lib/python3.9/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwags)
  File "/home/debian/PatrowlHears-master/backend_app/env/lib/python3.9/site-packages/django/db/backends/postgresql/base.py", line 187, in get_new_connection
    connection = Database.connect(**conn_params)
  File "/home/debian/PatrowlHears-master/backend_app/env/lib/python3.9/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: fe_sendauth: no password supplied
```
The errors seems to be occuring durring theses operations : 
```
# Apply database migrations
echo "[+] Make database migrations"
python manage.py makemigrations

# Apply database migrations
echo "[+] Apply database migrations"
python manage.py migrate
```

Also it seems that pip does not support a version of a module (the latest supported version is 5.0.0
```
ERROR: Could not find a version that satisfies the requirement djangorestframework-simplejwt==4.4.0
ERROR: No matching distribution found for djangorestframework-simplejwt==4.4.0
```
I'm Using Debian 11: 
```
Distributor ID: Debian
Description:    Debian GNU/Linux 11 (bullseye)
Release:        11
Codename:       bullseye
```

Could you help me fix this issue ?
Thanks

**Comment by MaKyOtOx** [comment]
Hi there !
Looks like a common issue.
Could please check you postgresql configuration file `pg_hba.conf` allow local authentication with login/password ?

**Comment by sbnsec** [comment]
Thanks for your help, i solved the issue by adding the PostgreSQL password in Django : 

https://github.com/Patrowl/PatrowlHears/pull/155
